### ISSUE TITLE
Failure to start journal.

### ISSUE THREAD

**Issue by Thell** [dockerimages/docker-systemd#1]
An attempt to start this image with a host running Ubuntu 15.04 resulted in a failure to start the journal service and was confirmed by another user on the docker irc channel. The dmesg output shows multiple

'''
aufs au_opts_verify:1612:docker[12611]: dirperm1 breaks the protection by the permission bits on the lower branch
'''
and
'''
audit: type=1400 audit(1430574607.811:627): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="docker-default" name="/sys/fs/cgroup/" pid=10991 comm="systemd" flags="ro, nosuid, nodev, noexec, remount, strictatime"
'''

The output described in the readme for the second example:

'''
docker run -it --cap-add SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro dockerimages/docker-systemd " "
'''

indicates success making me think it had/has something to do with the host setup so I attempted using the docker master build with --storage-opts to both enable and disable dirperm1 aufs mount topion, which didn't help, and attempted using the overlay storage driver which also didn't work. Within the container, altering the journald.conf to use volatile, or persistent (after creating the journal path) also didn't help.

Have there been any reports of success on a stock ubuntu 15.04 host?

**Comment by frank-dspeed** [comment]
I Will verifiy that on vanilla 15.04 but your right it could be host setup at all the output you saw was from a ubuntu 14.10 host but i log all changes i do to host it can't be much will inform you about that

**Comment by frank-dspeed** [comment]
PLZ i have a question is your ubuntu 15.04 running systemd? because this img only works if your host runns systemd already as pid 1 init.

**Comment by Thell** [comment]
Yes.

**Comment by ivan1986** [comment]
Same issue when host running on ubuntu 15.04 systemd

systemd-journald[35]: Failed to join audit multicast group: Operation not permitted

root@a73d2f04a5aa:~# systemctl start systemd-journald-audit.socket
systemd-journald-audit.socket failed to listen on sockets: Operation not permitted

**Comment by Thell** [comment]
CAP_AUDIT_READ needs to be available... There are issues with this on Windows.  
( see https://github.com/docker/docker/pull/13016 )

**Comment by ivan1986** [comment]
ubuntu 15.10 systemd 222 works fine

**Comment by Thell** [comment]
:+1:
