### ISSUE TITLE
Real need cgroup mapping?

### ISSUE THREAD

**Issue by ivan1986** [dockerimages/docker-systemd#3]
with this not run on last boot2docker (coreOS)
-v /sys/fs/cgroup:/sys/fs/cgroup:ro
testing on linux with systemd v222 - works fine
not found any issues - any systems starts
some fixes between 218 and 222?

**Comment by frank-dspeed** [comment]
hehehehehehehe you need to understand cgroups read about it a bit maybe it runs thats sure possible but then it runs at last in wrong namespace
